spring.application.name=CorporateCertificationPortal

# MariaDB Database
spring.datasource.url=jdbc:mariadb://localhost:3306/corporate_certification_portal_db
spring.datasource.username=root
spring.datasource.password=asdf
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Local file upload directory
app.upload.dir=uploads
